# ≥50 common spam words/domains/brands
keywords:
  - slot
  - judol
  - gacor
  - maxwin
  - scatter
  - rtp
  - bonanza
  - wild
  - jackpot
  - casino
  - bet
  - togel
  - slot88
  - slot77
  - slot69
  - pragmatic
  - olxtoto
  - olympus
  - zeus
  - sweet bonanza
  - starlight
  - princess
  - mahjong
  - ways
  - riches
  - aztec
  - gems
  - habanero
  - pgsoft
  - microgaming
  - betwin
  - idr
  - deposit
  - withdraw
  - garansi
  - spin
  - naga
  - maxbet
  - sbobet
  - royal
  - bonus new member
  - bonus harian
  - slotmania
  - betting
  - slotku
  - slotindo
  - slotviral
  - slotmax
  - slotking
  - slotserver
  - slotgila
  - slotjitu
  - slotmantap
  - slotpulsa
  - slot pulsa tanpa potongan
  - gates
  - wild west gold
  - big bass
  - bonanza gold
  - aztec gems
  - five lions
  - koi gate
  - hot fiesta
  - wild bandito
  - treasure wild
  - super x
  - sugar rush
